version: "3"

services:
  web-server:
    restart: always
    build: .
    image: node-oracle
    container_name: blog_cms
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src
      - /usr/src/node_modules # No sobreescribir este directorio
