version: "3"

services:
  web-server:
    restart: always
    build: .
    environment:
      DB_URL: "postgres"
    depends_on: # Indica que este servicio tiene que iniciar después de la siguiente lista
      - postgres
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src
      - /usr/src/node_modules # No sobreescribir este directorio
  postgres:
    image: postgres:12.4-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: StickyMineSpartan117
