SELECT
    *
FROM
    ARTICULOS A;

SELECT
    ID_ARTICULO,
    TITULO,
    ENLACE_PERSONALIZADO,
    ID_USUARIO,
    PUBLICADO,
    FECHA_CREACION,
    FECHA_MODIFICACION,
    CONTENIDO
FROM
    ARTICULOS A
WHERE
    A .ID_USUARIO = :userId;
    
   
   
   
INSERT INTO USUARIOS (EMAIL, PASSWORDHASH, NOMBRE, APELLIDOS, GENERO)
SELECT
	'test.email@gmail.com',
	PASSWORDHASH,
	'leonardo',
	'arellano',
	'M'
FROM USUARIOS u
WHERE ID_USUARIO = 26;


SELECT 'LEONARDO', 3 , EMAIL, TO_DATE('19/10/1998', 'DD/MM/RR') FROM USUARIOS WHERE EMAIL = 'Daniela.Malave72@hotmail.com';


   
SELECT TO_DATE('19/10/1998', 'DD/MM/RR') FROM DUAL;